apiVersion: v1
kind: ConfigMap
metadata:
    name: script-config
data:
    test.sh: |
             #!/bin/sh
             echo "Hello from shell script!!!"
             while true; do
                sleep 60
             done
