apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: image-pruner-daemonset
spec:
    selector:
        matchLabels:
            app: image-pruner
    template:
        metadata:
            labels:
                app: image-pruner
            annotations:
                configmap-hash: "{{ .Values.configmap | sha256sum }}"
        spec:
            containers:
            -   name: ubuntu-container
                image: ubuntu:latest
                command: ["/bin/bash", "-c", "bash /script/test.sh"]
                securityContext:
                    privileged: true
                    runAsUser: 0
                volumeMounts:
                -   name: socket
                    mountPath: /run/k3s/containerd
                -   name: host-k3s
                    mountPath: /k3s
                -   name: script
                    mountPath: /script/
            volumes:
            -   name: socket
                hostPath:
                    path: /run/k3s/containerd
                    type: Directory
            -   name: host-k3s
                hostPath:
                    path: /usr/local/bin/k3s
                    type: File
            -   name: script
                configMap:
                    name: script-config

