apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: image-pruner-daemonset
spec:
    selector:
        matchLabels:
            app: image-pruner
    template:
        metadata:
            labels:
                app: image-pruner
        spec:
            containers:
            -   name: ubuntu-container
                image: ubuntu:latest
                command: ["/bin/bash"]
                args:
                -   "-c"
                -   |
                    ln -s /k3s /crictl
                    echo "runtime-endpoint: unix:///run/k3s/containerd/containerd.sock" > crictl.yaml
                    while true; do
                        ./crictl --config crictl.yaml rmi --prune
                        ./crictl --config crictl.yaml images
                    sleep 600
                    done
                securityContext:
                    privileged: true
                    runAsUser: 0
                volumeMounts:
                -   name: socket
                    mountPath: /run/k3s/containerd
                -   name: host-k3s
                    mountPath: /k3s
            volumes:
            -   name: socket
                hostPath:
                    path: /run/k3s/containerd
                    type: Directory
            -   name: host-k3s
                hostPath:
                    path: /usr/local/bin/k3s
                    type: File

