apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: disk-cleaner-daemonset
spec:
    selector:
        matchLabels:
            app: disk-cleaner
    template:
        metadata:
            labels:
                app: disk-cleaner
        spec:
            containers:
                - name: ubuntu-container
                  image: ubuntu:latest
                  ports:
                    containerPort: 80
