apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: image-pruner-daemonset
spec:
    selector:
        matchLabels:
            app: image-pruner
    template:
        metadata:
            labels:
                app: image-pruner
        spec:
            containers:
            -   name: ubuntu-container
                image: ubuntu:latest
                command: ["/bin/bash", "-c"]
                args:
                -   |
                    while true; do
                        sleep 600
                    done
                securityContext:
                    privileged: true
                    runAsUser: 0
                volumeMounts:
                -   name: host-crictl
                    mountPath: /crictl
                -   name: host-run
                    mountPath: /run
            volumes:
            -   name: host-crictl
                hostPath:
                    path: /usr/local/bin/k3s
                    type: File
            -   name: host-run
                hostPath:
                    path: /run
                    type: Directory
              
                  
 