apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: image-pruner-daemonset
spec:
    selector:
        matchLabels:
            app: image-pruner
    template:
        metadata:
            labels:
                app: image-pruner
        spec:
            containers:
                - name: ubuntu-container
                  image: ubuntu:latest
                  command: ["/bin/bash", "-c"]
                  args:
                    - |
                      while true; do
                          echo "Running image-pruning script..."
                          crictl rmi --prune
                          sleep 600
                      done