apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    version: v1.3
spec:
  containers:
    - name: nginx
      image: python-3.11-slim
      ports:
        - containerPort: 80
